#!/usr/bin/env python3
"""Emit Turmeric `extern-c` declarations for the godot-* natives.

The AOT path stages a script into a transient project and compiles it with
standalone `tur`, which has never heard of any godot-* name -- so the staged
build dies at the first one. These declarations are what the staged project
needs in order to elaborate; the matching exported C entry points in the
GDExtension are what it needs in order to link.

Reads tools/native_signatures.py. Only the FIXED table is emitted: VARIADIC,
POLYMORPHIC and CLOSURE have no single C signature and are listed as comments
instead, so the gap is visible in the output rather than silently absent.

Usage:
    python3 tools/gen_native_decls.py [--out <path>]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import native_signatures as NS  # noqa: E402

HEADER = """\
;;; godot-natives -- extern-c declarations for the GDExtension's natives.
;;;
;;; AUTO-GENERATED by tools/gen_native_decls.py -- DO NOT EDIT.
;;; Regenerate when tools/native_signatures.py changes.
;;;
;;; Staged into the AOT project so `tur` can elaborate a script that calls the
;;; Godot API. Without these every staged build stops at the first godot-* name
;;; with `unknown function or operator`, which is
;;; docs/reported/godot-aot-staged-build-lacks-godot-natives.md.
;;;
;;; The C symbols these resolve to are the compiler's own mangling of the
;;; Turmeric names (`-` and `>` and `?` all become `_`), so the GDExtension has
;;; to export entry points under exactly those names. Both halves are generated
;;; from one table precisely so they cannot drift.
;;;
;;; NOT DECLARED HERE, because no single C signature describes them --
;;; see the tail of this file for the list and the reason.
"""


def decl(name, ret, params):
    ps = " ".join("a%d %s" % (i, t) for i, t in enumerate(params))
    return "(extern-c %s [%s] %s)" % (name, ps, ret)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    lines = [HEADER]
    for name in sorted(NS.FIXED):
        ret, params, prov = NS.FIXED[name]
        lines.append(decl(name, ret, params))

    lines.append("")
    lines.append(";;; ---------------------------------------------------------------")
    lines.append(";;; Deliberately absent (%d of %d). Each needs a decision, not a"
                 % (len(NS.VARIADIC) + len(NS.POLYMORPHIC) + len(NS.CLOSURE),
                    len(NS.ALL_NAMES)))
    lines.append(";;; declaration, and a wrong guess here is a silent ABI mismatch that")
    lines.append(";;; neither the compiler nor the linker can catch.")
    lines.append(";;;")
    lines.append(";;; VARIADIC -- arity varies per call site; these are the busiest")
    lines.append(";;; names in the surface (godot-call-v: 1116 call sites, 13 arities).")
    for name in sorted(NS.VARIADIC):
        ret, ars = NS.VARIADIC[name]
        lines.append(";;;   %-20s %-7s arities %s" % (name, ret, ars))
    lines.append(";;;")
    lines.append(";;; POLYMORPHIC -- one slot accepts several tags.")
    for name in sorted(NS.POLYMORPHIC):
        ret, sig, why = NS.POLYMORPHIC[name]
        lines.append(";;;   %-20s %-7s %s" % (name, ret, why))
    lines.append(";;;")
    lines.append(";;; CLOSURE -- a code pointer plus a captured environment, which")
    lines.append(";;; cannot cross an extern-c boundary as a scalar.")
    for name in sorted(NS.CLOSURE):
        ret, sig, why = NS.CLOSURE[name]
        lines.append(";;;   %-20s %-7s %s" % (name, ret, why))

    text = "\n".join(lines) + "\n"
    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote %s (%d declarations)" % (args.out, len(NS.FIXED)))
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
